- name: CryoSPARC CycleCloud project
  block:
    - name: Read CryoSPARC admin password from KV
      command: az keyvault secret show --vault-name {{key_vault}} -n {{database_user}}-password --query "value" -o tsv
      delegate_to: localhost
      connection: local
      register: cryosparc_admin_pwd
      become: false

    - name: Create cryosparc project
      command: '/usr/local/bin/cyclecloud project init cryosparc'
      args:
        chdir: '{{project_root}}'
        creates: '{{cryosparc_project_root}}/project.ini'

    - name: Create common cryosparc project scripts
      template:
        src: '{{role_path}}/projects/cryosparc/cluster-init/scripts/{{ item }}.j2'
        dest: '{{cryosparc_project_root}}/specs/default/cluster-init/scripts/{{ item }}'
        mode: 0777
      with_items:
        - 01-setup_data_disk.sh
        - 02-download_cryosparc.sh
        - 03-install_cryosparc.sh
        - 05-install_app_menu_shortcut.sh

    - name: Create import Slurm cluster project script
      template:
        src: '{{role_path}}/projects/cryosparc/cluster-init/scripts/04-import_slurm_cluster.sh.j2'
        dest: '{{cryosparc_project_root}}/specs/default/cluster-init/scripts/04-import_slurm_cluster.sh'
        mode: 0777
      when: cc_queue_manager == "slurm"

    - name: Copy CryoSPARC Slurm cluster definition files
      copy:
        src: '{{role_path}}/projects/cryosparc/cluster-init/files/slurm_{{ item }}'
        dest: '{{cryosparc_project_root}}/specs/default/cluster-init/files/{{ item }}'
      with_items:
        - cluster_info.json
        - cluster_script.sh
      when: cc_queue_manager == "slurm"

    - name: Copy CryoSPARC app shortcut files
      copy:
        src: '{{role_path}}/projects/cryosparc/cluster-init/files/{{ item }}'
        dest: '{{cryosparc_project_root}}/specs/default/cluster-init/files/{{ item }}'
      with_items:
        - cryosparc.desktop
        - cryosparc_16.png

    - name: Upload cryosparc CycleCloud project
      command: '/usr/local/bin/cyclecloud project upload'
      args:
        chdir: '{{cryosparc_project_root}}'
  when: cryosparc_enabled == true
